# Site settings
title: Laboratório de Rua
email: labderua@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Laboratório de Rua.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: labrua
facebook_username: LabRua
instagram_username: lab.rua

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 4
paginate_path: "blog/page:num"
